package com.pr.logpractice

import groovy.json.JsonBuilder

import static net.grinder.script.Grinder.grinder
import static org.junit.Assert.*
import static org.hamcrest.Matchers.*
import net.grinder.script.GTest
import net.grinder.script.Grinder
import net.grinder.scriptengine.groovy.junit.GrinderRunner
import net.grinder.scriptengine.groovy.junit.annotation.BeforeProcess
import net.grinder.scriptengine.groovy.junit.annotation.BeforeThread
// import static net.grinder.util.GrinderUtils.* // You can use this if you're using nGrinder after 3.2.3
import org.junit.Before
import org.junit.BeforeClass
import org.junit.Test
import org.junit.runner.RunWith

import org.ngrinder.http.HTTPRequest
import org.ngrinder.http.HTTPRequestControl
import org.ngrinder.http.HTTPResponse
import org.ngrinder.http.cookie.Cookie
import org.ngrinder.http.cookie.CookieManager

/**
 * A simple example using the HTTP plugin that shows the retrieval of a single page via HTTP.
 *
 * This script is automatically generated by ngrinder.
 *
 * @author admin
 */
@RunWith(GrinderRunner)
class Diary {

    public static GTest test1
    public static GTest test2
    public static GTest test3
    public static GTest test4

    public static HTTPRequest request
    public static Map<String, String> headers = [:]
    public static Map<String, Object> params = [:]
    public static List<Cookie> cookies = []

    @BeforeProcess
    public static void beforeProcess() {
        HTTPRequestControl.setConnectionTimeout(300000)
        test1 = new GTest(1, "/v1/diaries?page=0~500&size=10")
        test2 = new GTest(2, "/v1/diaries/100007~105488")
        test3 = new GTest(3, "/v1/diaries/marker/1")
        test4 = new GTest(4, "/v1/diaries/location?right_latitude=40.0&right_longitude=40.0&left_latitude=0.0&left_longitude=0.0")
        request = new HTTPRequest()
        headers.put("Authorization", "Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJraW1zazMxMTNAbmF2ZXIuY29tIiwiYXV0aCI6IkdVRVNUIiwiZXhwIjoxNzAwOTQyMTI0fQ.ogrEboGlF5w3f4Y7fL25eSwAf2U8njtFkm0LcuO-u5o")
        grinder.logger.info("프로세스 시작 전")
    }

    @BeforeThread
    public void beforeThread() {
        test1.record(this, "test1")
        test2.record(this, "test2")
        test3.record(this, "test3")
        test4.record(this, "test4")
        grinder.statistics.delayReports = true
        //grinder.logger.info("스레드 시작 전")
    }

    @Before
    public void before() {
        request.setHeaders(headers)
        CookieManager.addCookies(cookies)
        //grinder.logger.info("헤더 쿠키 초기화")
    }

    @Test
    public void test1() {
        //다이어리 목록 조회 페이지네이션
        int minPage = 0;
        int maxPage = 500;
        Random random = new Random();
        int randomPage = random.nextInt(maxPage - minPage + 1) + minPage;

        String paginationUrl = "/v1/diaries?page=" + randomPage + "&size=10";
        HTTPResponse response = request.GET(paginationUrl, params)

        if (response.statusCode == 200) {
            grinder.logger.info("다이어리 목록 조회 성공: {}", response.statusCode)

        } else {
            grinder.logger.info("다이어리 목록 조회 실패 응답: {}", response.getBodyText())
            grinder.logger.error("다이어리 목록 조회 실패: {}", response.statusCode)
        }

        assertThat(response.statusCode, is(200))
    }

    @Test
    public void test2() {
        // 랜덤한 다이어리 상세 조회 (couple_id 1에 해당하는 회원의 다이어리 중 랜덤임)
        int minId = 100007;
        int maxId = 105488;
        Random random = new Random();
        int randomDiaryId = random.nextInt(maxId - minId + 1) + minId;

        HTTPResponse response = request.GET("https://love-back.kro.kr/v1/diaries/" + randomDiaryId, params)

        if (response.statusCode == 200) {
            grinder.logger.info("다이어리 상세 조회 성공: {}", response.statusCode)
        } else {
            grinder.logger.info("다이어리 상세 조회 실패 응답: {}", response.getBodyText())
            grinder.logger.error("다이어리 상세 조회 실패: {}", response.statusCode)
        }

        assertThat(response.statusCode, is(200))

    }

    @Test
    public void test3() {
        //마커로 조회

        HTTPResponse response = request.GET("https://love-back.kro.kr/v1/diaries/marker/1", params)

        if (response.statusCode == 200) {
            grinder.logger.info("마커로 조회 성공: {}", response.statusCode)
        } else {
            grinder.logger.error("마커로 조회 실패 응답: {}", response.statusCode)
            grinder.logger.info("마커로 조회 응답: {}", response.getBodyText())

        }

        assertThat(response.statusCode, is(200))
    }

    @Test
    public void test4() {
        // 좌표로 조회
        HTTPResponse response = request.GET("https://love-back.kro.kr/v1/diaries/location?right_latitude=40.0&right_longitude=40.0&left_latitude=0.0&left_longitude=0.0", params)

        if (response.statusCode == 200) {
            grinder.logger.info("좌표로 조회 성공: {}", response.statusCode)
        } else {
            grinder.logger.info("좌표로 조회 실패 응답: {}", response.getBodyText())
            grinder.logger.error("좌표로 조회 실패: {}", response.statusCode)
        }

        assertThat(response.statusCode, is(200))

    }
}
